name: Kolibri game build

on:
  push:

jobs:
  build:
    name: Build for Android and iOS
    runs-on: ubuntu-latest
    container:
      image: unityci/editor:ubuntu-6000.0.45f1-android-3.1.0
    strategy:
      matrix: # to build both platforms in parallel
        targetPlatform: [Android, iOS] 

    steps:
      - name: Checkout
        uses: actions/checkout@v3     

      - name: Build project
        # Trigger a custom build backend script
        run: |
          .github/scripts/build.sh ${{ matrix.targetPlatform }}

      - name: Install Dependency-Check
        run: |
          sudo apt-get update
          sudo apt-get install -y dependency-check

      - name: Run Dependency-Check
        run: |
          dependency-check --project "UnityProject" --scan ./Assets --out ./dependency-check-report
      # Perhaps this is a bad config for a Unity project, but the point is there

      - name: Upload ${{ matrix.targetPlatform }} build artefacts to Azure Blob Storage
        uses: azure/CLI@v1
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
          DESTINATION: unity_mobile_plugin/builds/${{ matrix.targetPlatform }}/${{ github.ref_type == 'tag' && github.ref_name || github.sha }}
          # in case the build is of a tag the destination path
          # is like  unity_mobile_plugin/builds/android-or-ios/v1.2.3/
          # but in case its anthing else
          # its is like unity_mobile_plugin/builds/android-or-ios/abc123asfasf_git_commit_hash/ 
        with:
          azcliversion: 2.30.0
          inlineScript: |
            echo "Uploading build to Azure Blob Storage..."
            az storage blob upload-batch \
              --account-name $AZURE_STORAGE_ACCOUNT \
              --destination ${{ env.DESTINATION }} \
              --source build/${{ matrix.targetPlatform }} \
              --auth-mode key